###
POST http://localhost:8080/produce
Content-Type: application/json

{
  "topicId": "test",
  "message": "1"
}

###
POST http://localhost:8082/topics
Content-Type: application/json

{
  "topicId": "test5"
}