spring:
  application:
    name: message-queue

management:
  endpoints:
    web:
      exposure:
        include: "*"

cluster:
  nodes:
  - id: 1
    role: LEADER
    host: localhost
    port: 8080
  - id: 2
    role: FOLLOWER
    host: localhost
    port: 8081
  - id: 3
    role: FOLLOWER
    host: localhost
    port: 8082

node:
  id: 1
